# Generated by Django 2.2.1 on 2019-05-13 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionCode', models.CharField(blank=True, max_length=100, null=True)),
                ('process_department', models.CharField(max_length=20)),
                ('process_ent_id', models.CharField(max_length=20)),
                ('submitted_by', models.CharField(editable=False, max_length=20)),
                ('project', models.CharField(editable=False, max_length=30)),
                ('asset', models.CharField(editable=False, max_length=30)),
                ('version', models.CharField(editable=False, max_length=30)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comments', models.TextField(max_length=100)),
            ],
        ),
    ]
