# Generated by Django 2.2.1 on 2019-05-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondetails',
            name='file_path',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissiondetails',
            name='comments',
            field=models.TextField(max_length=50),
        ),
    ]
