# Generated by Django 2.2.1 on 2019-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20190513_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiondetails',
            name='comments',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submissiondetails',
            name='project',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
