# Generated by Django 2.2.1 on 2019-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20190513_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondetails',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='time_to_upload_in_seconds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='uploaded_file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
