# Generated by Django 2.2.1 on 2019-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_auto_20190514_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondetails',
            name='asset_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='final_upload_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='ftplib_chunk_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='logs',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='project_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='python_chunk_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='readable_file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='time_to_upload_in_hms',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
