# Generated by Django 2.2.1 on 2019-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_auto_20190516_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondetails',
            name='test_average_upload_speed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissiondetails',
            name='test_ftp_upload_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
