# Generated by Django 2.2.1 on 2019-05-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20190517_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiondetails',
            name='logs',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
